# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.provider "virtualbox" do |vb, override|
    vb.memory = "1024"
    override.vm.network "forwarded_port", guest: 80, host: 8202
  end
  config.vm.provision "shell", path: "provision.sh"
end
